name: 'codeql-dependency-graph-action'
description: 'Advance Security Policy as Code'

inputs:
  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    # Make sure 3.10 is installed
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m codeqldepgraph \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}" \
          ${{ inputs.argvs }}
